apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 8000;
        server_name localhost;

        root /var/www/html/public;

        index index.php index.html;

        # Mengarahkan permintaan biasa ke Laravel
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Konfigurasi untuk /metrics
        location /metrics {
            try_files $uri /index.php$is_args$args;
        }

        # Konfigurasi PHP-FPM
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass laravel-app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Logging
        error_log /var/log/nginx/laravel_error.log;
        access_log /var/log/nginx/laravel_access.log;
    }
