helm:
  parameters:
  - name: image.name
    value: ghcr.io/hngkhermn/multiple-app
    forcestring: true
  - name: image.tag
    value: latest@sha256:2836be65c0f17b746531118cf7e51adceb27bffb957e96d079795426a13ff47e
    forcestring: true
