helm:
  parameters:
  - name: image.name
    value: ghcr.io/hngkhermn/multiple-app
    forcestring: true
  - name: image.tag
    value: latest@sha256:095ab801edef72a0fc79f08a1faa4b054241382ba27a8bd03c1af783e5d60b04
    forcestring: true
