helm:
  parameters:
  - name: image.name
    value: ghcr.io/hngkhermn/multiple-app
    forcestring: true
  - name: image.tag
    value: latest@sha256:81589e4fbc7c41288b5574a0158e05768a1469c6e06f40740fed82e2d4b14211
    forcestring: true
