helm:
  parameters:
  - name: image.name
    value: ghcr.io/hngkhermn/multiple-app
    forcestring: true
  - name: image.tag
    value: latest@sha256:e688cd689fccee932a91e48f3d84b59578a7b0ffb17f4fe06265dfaa165ad6f2
    forcestring: true
