apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: php-fpm
          image: "{{ .Values.laravel.image.repository }}:{{ .Values.laravel.image.tag }}"
          imagePullPolicy: {{ .Values.laravel.image.pullPolicy }}
          ports:
            - containerPort: 9000
