apiVersion: v1
kind: Service
metadata:
  name: db-server
spec:
  selector:
    app: db-server
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
