apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr=ghcr.io/hngkhermn/multiple-app
    argocd-image-updater.argoproj.io/ghcr.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/ghcr.pull-secret: pullsecret:argocd/ghcr-credentials
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/hngkhermn/gitops-repo.git
    path: laravel-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true